CREATE TABLE BMS_BOOK_INFO (
  BOOK_ID LONG AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(45) NOT NULL,
  AUTHOR VARCHAR(45) NOT NULL,
  ISBN VARCHAR(45) NOT NULL,
  PUBLISHER VARCHAR(45) NULL,
  EDITION VARCHAR(45) NULL,
  LANGUAGE VARCHAR(45) NOT NULL,
  GENRE VARCHAR(45) NOT NULL,
  PUB_YEAR INT NULL,
  SUMMARY MEDIUMTEXT NULL,
  CONSTRAINT UNIQUE_ISBN UNIQUE (ISBN)
  );



CREATE TABLE BMS_BOOK_INV (
		  INV_ID LONG AUTO_INCREMENT PRIMARY KEY,
		  ISBN VARCHAR(45) NOT NULL,
		  QTY INT NOT NULL,
		  CONSTRAINT UNIQUE_ISBN1 UNIQUE (ISBN)
		  );