CREATE TABLE BMS_BOOK_INFO (
  BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(45) NOT NULL,
  AUTHOR VARCHAR(45) NOT NULL,
  ISBN VARCHAR(45) NULL,
  PUBLISHER VARCHAR(45) NULL,
  EDITION VARCHAR(45) NULL,
  LANGUAGE VARCHAR(45) NOT NULL,
  GENRE VARCHAR(45) NOT NULL,
  PUB_YEAR INT NULL,
  SUMMARY MEDIUMTEXT NULL
  );
